### ISSUE TITLE
The order of samples in "clust" files

### ISSUE THREAD

**Issue by SC-Duan** [grafau/discretize#1]
Hi,
"clust" files contain a clustering barplot, what the order of the samples? Is it coincident with the order of my meta information file? And how can I get the data to plot Supplementary figure 12?
Thank you!

**Comment by grafau** [comment]
Hi,

It is a little messy, sorry! The ordering is described here:

```
# sort and order individuals
	cent <- matrix(NA, k,2)
	for (o in 1:k)
	{
		cent[o,1] <- mean(meta[which(clu$clustering ==o),2])
		cent[o,2] <- mean(meta[which(clu$clustering ==o),3])
	}
	ind <- hclust(dist(cent))
	ord0 <- order(ind$order)[clu$silinfo$widths[,1]]
	ord1 <- as.numeric(substring(row.names(clu$silinfo$widths[order(ord0),]),2))

```

First, for each cluster ("subpopulation") a geographic centroid is calculated in "cent" object.
These centroids are hierarchically clustered to order "subpopulations", ie. get those that are geographically proximal to be next to each other.
Within each "subpopulation" individuals are ordered based on silhouette scores.

Regarding the Fig. S12 there are 3 panels for each "k" : 1) panel showing cluster ("subpopulation") affiliation, 2) panel showing cluster ("subpopulation") affiliation, but those with silhouette scores below threshold are greyed-out, and 3) admixture plot sorted as those above.

HTH

**Comment by SC-Duan** [comment]
Thank you!
